development: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db_development
  timeout: 5000

test:
  <<: *default
  database: tdd_example_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
